version: "3.6"

services:
  objectstorage:
    container_name: objectstorage
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z.fips
    mem_limit: 1024m
    restart: always
    env_file:
      - ./objectstorage.env
    command: server /data --console-address ":9001"
    labels:
      - "traefik.enable=true"

      ## Server
      - "traefik.http.routers.datatools-minio.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.datatools-minio.entrypoints=websecure"
      - "traefik.http.routers.datatools-minio.service=myminio"
      - "traefik.http.services.myminio.loadbalancer.server.port=9000"
      - "traefik.http.routers.datatools-minio.tls=true"
      - "traefik.http.routers.datatools-minio.tls.certresolver=myresolver"

      ## Console
      - "traefik.http.routers.datatools-minioc.rule=Host(`$CONSOLE_DOMAIN_NAME`)"
      - "traefik.http.routers.datatools-minioc.entrypoints=websecure"
      - "traefik.http.routers.datatools-minioc.service=myminioc"
      - "traefik.http.services.myminioc.loadbalancer.server.port=9001"
      - "traefik.http.routers.datatools-minioc.tls=true"
      - "traefik.http.routers.datatools-minioc.tls.certresolver=myresolver"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MINIO_DATA}:/data

    networks:
      - "apps-net"

networks:
  apps-net:
    external: true